# Generated by Django 3.1.6 on 2021-02-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210224_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
